// fg = estimated USDA MyPlate food group servings per item
// grains: oz-equivalents (1 slice bread = 1, ½ cup cooked pasta/rice = 1)
// veggies: cups (1 cup cooked or 2 cups raw leafy greens = 1)
// fruit:   cups (1 cup fresh/frozen = 1)
// dairy:   cups (1 cup milk/yogurt = 1, 1.5 oz hard cheese = 1)
// protein: oz-equivalents (1 egg = 1, 1 oz meat/fish = 1, 2 tbsp PB = 2)

const MEALS = [
  // ── Breakfast ──────────────────────────────────────────────────────────────
  // allDay:true = good at any meal time; shown in Lunch & Dinner palette tabs under "Anytime"
  { id: 'oatmeal',        name: 'Oatmeal + Banana',         emoji: '🥣', mealType: 'breakfast', allDay: true, protein: false, carbs: true,  note: 'Slow-release energy',
    fg: { grains: 2, fruit: 1 } },
  { id: 'eggs-toast',     name: 'Eggs + Toast',              emoji: '🍳', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,
    fg: { grains: 1, protein: 2 } },
  { id: 'scrambled-eggs', name: 'Scrambled Eggs',            emoji: '🍳', mealType: 'breakfast', allDay: true, protein: true,  carbs: false,
    fg: { protein: 2 } },
  { id: 'toast',          name: 'Toast',                     emoji: '🍞', mealType: 'breakfast', allDay: true, protein: false, carbs: true,
    fg: { grains: 1 } },
  { id: 'toast-butter',   name: 'Toast with Butter',         emoji: '🧈', mealType: 'breakfast', allDay: true, protein: false, carbs: true,
    fg: { grains: 1 } },
  { id: 'toast-pb',       name: 'Toast with Peanut Butter',  emoji: '🥜', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,
    note: 'Great pre-game or post-workout fuel', preGame: true,
    fg: { grains: 1, protein: 2 } },
  { id: 'yogurt',         name: 'Greek Yogurt + Granola',    emoji: '🫙', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,  dairy: true,
    fg: { grains: 1, dairy: 1, protein: 1 } },
  { id: 'smoothie',       name: 'Protein Smoothie',          emoji: '🥤', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,  dairy: true,
    fg: { dairy: 1, protein: 2, fruit: 0.5 } },
  { id: 'pancakes',       name: 'Pancakes',                  emoji: '🥞', mealType: 'breakfast', allDay: true, protein: false, carbs: true,
    fg: { grains: 2 } },
  { id: 'waffles',        name: 'Waffles',                   emoji: '🧇', mealType: 'breakfast', allDay: true, protein: false, carbs: true,
    fg: { grains: 2 } },
  { id: 'french-toast',   name: 'French Toast',              emoji: '🍞', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,
    fg: { grains: 2, protein: 1 } },
  { id: 'cereal',         name: 'Cereal + Milk',             emoji: '🥣', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,  dairy: true,
    fg: { grains: 1.5, dairy: 1 } },
  { id: 'bagel-cream',    name: 'Bagel + Cream Cheese',      emoji: '🥯', mealType: 'breakfast', allDay: true, protein: true,  carbs: true,  dairy: true,
    fg: { grains: 3, dairy: 0.5 } },
  { id: 'canadian-bacon', name: 'Canadian Bacon',            emoji: '🥓', mealType: 'breakfast', allDay: true, protein: true,  carbs: false,
    fg: { protein: 2 } },
  { id: 'ham',            name: 'Ham',                       emoji: '🍖', mealType: 'breakfast', allDay: true, protein: true,  carbs: false,
    fg: { protein: 2 } },

  // ── Lunch ──────────────────────────────────────────────────────────────────
  { id: 'chicken-rice',   name: 'Chicken + Rice',            emoji: '🍚', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, protein: 3 } },
  { id: 'turkey-sand',    name: 'Turkey Sandwich',           emoji: '🥪', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, protein: 3 } },
  { id: 'pasta-lunch',    name: 'Pasta + Marinara',          emoji: '🍝', mealType: 'lunch',  protein: false, carbs: true,  veggie: false,
    fg: { grains: 2.5, veggies: 0.5 } },
  { id: 'burrito-bowl',   name: 'Burrito Bowl',              emoji: '🌯', mealType: 'lunch',  protein: true,  carbs: true,  veggie: true,
    fg: { grains: 2, protein: 3, veggies: 1 } },
  { id: 'grilled-cheese', name: 'Grilled Cheese + Tomato',   emoji: '🧀', mealType: 'lunch',  protein: true,  carbs: true,  veggie: true,  dairy: true,
    fg: { grains: 2, dairy: 1, veggies: 0.5 } },
  { id: 'soup-bread',     name: 'Soup + Bread',              emoji: '🍲', mealType: 'lunch',  protein: false, carbs: true,  veggie: true,
    fg: { grains: 1, veggies: 1 } },
  { id: 'mac-cheese',     name: 'Mac & Cheese',              emoji: '🧀', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false, dairy: true,
    fg: { grains: 2, dairy: 1 } },
  { id: 'quesadilla',     name: 'Cheese Quesadilla',         emoji: '🫓', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false, dairy: true,
    fg: { grains: 2, dairy: 1, protein: 1 } },
  { id: 'ramen',          name: 'Ramen Noodles',             emoji: '🍜', mealType: 'lunch',  protein: false, carbs: true,  veggie: false,
    fg: { grains: 2.5 } },
  { id: 'pasta-plain',    name: 'Pasta Noodles',             emoji: '🍝', mealType: 'lunch',  protein: false, carbs: true,  veggie: false,
    fg: { grains: 2.5 } },
  { id: 'fb-pizza',       name: 'French Bread Pizza',        emoji: '🥖', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, dairy: 1, protein: 2 } },
  { id: 'potato-soup',    name: 'Potato Soup',               emoji: '🥔', mealType: 'lunch',  protein: false, carbs: true,  veggie: false,
    fg: { veggies: 1 } },
  { id: 'tomato-soup',    name: 'Tomato Soup',               emoji: '🍅', mealType: 'lunch',  protein: false, carbs: true,  veggie: true,
    fg: { veggies: 1 } },
  { id: 'grilled-ch2',    name: 'Grilled Cheese',            emoji: '🧀', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false, dairy: true,
    fg: { grains: 2, dairy: 1 } },
  { id: 'grilled-chkn',  name: 'Grilled Chicken',           emoji: '🍗', mealType: 'lunch',  protein: true,  carbs: false, veggie: false, allDay: true,
    fg: { protein: 4 } },
  { id: 'fish-fillet',   name: 'Fish Fillet',               emoji: '🐟', mealType: 'lunch',  protein: true,  carbs: false, veggie: false, allDay: true,
    fg: { protein: 4 } },
  { id: 'bean-bowl',     name: 'Bean Bowl',                 emoji: '🫘', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false,
    fg: { protein: 3, veggies: 0.5 } },
  { id: 'tuna-wrap',     name: 'Tuna Wrap',                 emoji: '🌯', mealType: 'lunch',  protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, protein: 3 } },

  // ── Dinner ─────────────────────────────────────────────────────────────────
  { id: 'salmon',         name: 'Salmon + Veggies',          emoji: '🐟', mealType: 'dinner', protein: true,  carbs: false, veggie: true,
    fg: { protein: 4, veggies: 1 } },
  { id: 'stir-fry',       name: 'Chicken Stir Fry',          emoji: '🍜', mealType: 'dinner', protein: true,  carbs: true,  veggie: true,
    fg: { grains: 1.5, protein: 3, veggies: 1 } },
  { id: 'pasta-bol',      name: 'Pasta Bolognese',           emoji: '🍝', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2.5, protein: 3 } },
  { id: 'tacos',          name: 'Tacos',                     emoji: '🌮', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 1.5, protein: 3 } },
  { id: 'pizza',          name: 'Pizza',                     emoji: '🍕', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, dairy: 1.5, protein: 2 } },
  { id: 'chicken-rice2',  name: 'Chicken + Rice + Veggies',  emoji: '🍗', mealType: 'dinner', protein: true,  carbs: true,  veggie: true,
    fg: { grains: 2, protein: 3, veggies: 1 } },
  { id: 'burger',         name: 'Burger',                    emoji: '🍔', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, protein: 4 } },
  { id: 'mashed-potato',  name: 'Mashed Potatoes',           emoji: '🥔', mealType: 'dinner', protein: false, carbs: true,  veggie: false,
    fg: { veggies: 1 } },
  { id: 'perogies',       name: 'Perogies',                  emoji: '🥟', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, dairy: 0.5, protein: 1 } },
  { id: 'bacon-pizza',    name: 'Bacon Pizza',               emoji: '🍕', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, dairy: 1.5, protein: 3 } },
  { id: 'pizzadilla',     name: 'Bacon Pizzadilla',          emoji: '🍕', mealType: 'dinner', protein: true,  carbs: true,  veggie: false,
    fg: { grains: 2, dairy: 1.5, protein: 3 } },
];

const SNACKS = [
  // ── Hydration ──────────────────────────────────────────────────────────────
  { id: 'water',         name: 'Water (glass)',              emoji: '💧', treat: false, protein: false, carbs: false, water: true },
  { id: 'sports-drink',  name: 'Sports Drink',               emoji: '🏃', treat: false, protein: false, carbs: true,  water: true,  note: 'Good during intense workouts' },
  { id: 'coconut-water', name: 'Coconut Water',              emoji: '🥥', treat: false, protein: false, carbs: true,  water: true,  note: 'Natural electrolytes' },

  // ── Pre-game picks ─────────────────────────────────────────────────────────
  { id: 'banana',        name: 'Banana',                     emoji: '🍌', treat: false, protein: false, carbs: true,  postWorkout: true,  preGame: true,  note: 'Quick energy — great before games!',
    fg: { fruit: 1 } },
  { id: 'toast-honey',   name: 'Toast + Honey',              emoji: '🍞', treat: false, protein: false, carbs: true,  postWorkout: false, preGame: true,  note: 'Easy carbs — top pre-game pick',
    fg: { grains: 1 } },
  { id: 'orange-slices', name: 'Orange Slices',              emoji: '🍊', treat: false, protein: false, carbs: true,  postWorkout: false, preGame: true,  note: 'Classic halftime & pre-game snack!',
    fg: { fruit: 0.5 } },
  { id: 'granola-bar',   name: 'Granola Bar',                emoji: '🍫', treat: false, protein: false, carbs: true,  postWorkout: false, preGame: true,
    fg: { grains: 1 } },
  { id: 'rice-plain',    name: 'Rice Cakes (plain)',         emoji: '🥜', treat: false, protein: false, carbs: true,  postWorkout: false, preGame: true,  note: 'Easy on the stomach pre-game',
    fg: { grains: 1 } },

  { id: 'pretzels',      name: 'Pretzels',                   emoji: '🥨', treat: false, protein: false, carbs: true,  postWorkout: false, preGame: true,  note: 'Easy carbs, low fat — solid pre-game snack',
    fg: { grains: 1 } },

  // ── Healthy snacks ─────────────────────────────────────────────────────────
  { id: 'fruit-smoothie', name: 'Fruit Smoothie',              emoji: '🥤', treat: false, protein: false, carbs: true,  postWorkout: false, preGame: true,  note: 'Natural fruit energy — great before activity',
    fg: { fruit: 1 } },
  { id: 'apple-pb',      name: 'Apple + Peanut Butter',      emoji: '🍎', treat: false, protein: true,  carbs: true,  postWorkout: true,  preGame: false,
    fg: { fruit: 0.5, protein: 2 } },
  { id: 'choc-milk',     name: 'Chocolate Milk',             emoji: '🥛', treat: false, protein: true,  carbs: true,  postWorkout: true,  preGame: false, dairy: true, note: 'Best post-workout drink!',
    fg: { dairy: 1, protein: 1 } },
  { id: 'trail-mix',     name: 'Trail Mix',                  emoji: '🥜', treat: false, protein: true,  carbs: true,  postWorkout: false, preGame: false,
    fg: { protein: 1, fruit: 0.25 } },
  { id: 'cheese-crack',  name: 'Cheese + Crackers',          emoji: '🧀', treat: false, protein: true,  carbs: true,  postWorkout: false, preGame: false, dairy: true,
    fg: { grains: 1, dairy: 0.5, protein: 1 } },
  { id: 'hummus-vegg',   name: 'Hummus + Veggies',           emoji: '🥕', treat: false, protein: true,  carbs: false, postWorkout: false, preGame: false,
    fg: { veggies: 0.5, protein: 1 } },
  { id: 'protein-bar',   name: 'Protein Bar',                emoji: '💪', treat: false, protein: true,  carbs: true,  postWorkout: true,  preGame: false,
    fg: { grains: 1, protein: 2 } },
  { id: 'cottage-ch',    name: 'Cottage Cheese + Fruit',     emoji: '🫙', treat: false, protein: true,  carbs: true,  postWorkout: true,  preGame: false, dairy: true,
    fg: { dairy: 0.5, protein: 2, fruit: 0.5 } },
  { id: 'rice-cakes',    name: 'Rice Cakes + Peanut Butter', emoji: '🥜', treat: false, protein: true,  carbs: true,  postWorkout: true,  preGame: false,
    fg: { grains: 1, protein: 2 } },
  { id: 'string-ch',     name: 'String Cheese',              emoji: '🧀', treat: false, protein: true,  carbs: false, postWorkout: false, preGame: false, dairy: true,
    fg: { dairy: 0.5, protein: 1 } },
  { id: 'yogurt-plain',  name: 'Yogurt (plain/vanilla)',     emoji: '🫙', treat: false, protein: true,  carbs: false, postWorkout: true,  preGame: false, dairy: true,
    fg: { dairy: 1, protein: 1 } },
  { id: 'milk-snack',    name: 'Glass of Milk',              emoji: '🥛', treat: false, protein: true,  carbs: false, postWorkout: true,  preGame: false, dairy: true,
    fg: { dairy: 1, protein: 1 } },
  { id: 'cheese-slice',  name: 'Cheese Slice',               emoji: '🧀', treat: false, protein: true,  carbs: false, postWorkout: false, preGame: false, dairy: true,
    fg: { dairy: 0.67, protein: 1 } },
  { id: 'edamame',       name: 'Edamame',                    emoji: '🫘', treat: false, protein: true,  carbs: false, postWorkout: false, preGame: false,
    fg: { veggies: 0.5, protein: 2 } },

  // ── Treats — no food group contribution (discretionary calories) ────────────
  { id: 'ice-cream',     name: 'Ice Cream',                  emoji: '🍦', treat: true,  protein: false, carbs: true,  dairy: true, fg: { dairy: 0.5 } },
  { id: 'candy',         name: 'Candy',                      emoji: '🍬', treat: true,  protein: false, carbs: true  },
  { id: 'cookies',       name: 'Cookies',                    emoji: '🍪', treat: true,  protein: false, carbs: true  },
  { id: 'chips',         name: 'Chips',                      emoji: '🥨', treat: true,  protein: false, carbs: true  },
  { id: 'soda',          name: 'Soda (small)',                emoji: '🥤', treat: true,  protein: false, carbs: true  },
  { id: 'brownie',       name: 'Brownie',                    emoji: '🍫', treat: true,  protein: false, carbs: true  },
];

// Sides attach to a meal slot — don't count as snacks, contribute to meal balance.
// fruit/veggie/dairy flags drive the balance compliance check; fg drives food group totals.
const SIDES = [
  // ── Fruit ──────────────────────────────────────────────────────────────────
  { id: 'side-banana',     name: 'Banana',              emoji: '🍌', fruit: true,  fg: { fruit: 1    } },
  { id: 'side-apple',      name: 'Apple Slices',         emoji: '🍎', fruit: true,  fg: { fruit: 0.5  } },
  { id: 'side-berries',    name: 'Berries',              emoji: '🫐', fruit: true,  fg: { fruit: 0.5  } },
  { id: 'side-orange',     name: 'Orange Slices',        emoji: '🍊', fruit: true,  fg: { fruit: 0.5  } },
  { id: 'side-grapes',     name: 'Grapes',               emoji: '🍇', fruit: true,  fg: { fruit: 0.5  } },
  { id: 'side-strawberry', name: 'Strawberries',         emoji: '🍓', fruit: true,  fg: { fruit: 0.5  } },
  { id: 'side-melon',      name: 'Melon / Watermelon',   emoji: '🍉', fruit: true,  fg: { fruit: 1    } },
  { id: 'side-peach',      name: 'Peach',                emoji: '🍑', fruit: true,  fg: { fruit: 0.5  } },
  { id: 'side-oj',         name: 'Orange Juice',         emoji: '🍊', fruit: true,  fg: { fruit: 1    } },
  { id: 'side-applesauce', name: 'Applesauce',           emoji: '🍏', fruit: true,  fg: { fruit: 0.5  } },
  // ── Vegetables ─────────────────────────────────────────────────────────────
  { id: 'side-carrots',    name: 'Carrot Sticks',        emoji: '🥕', veggie: true, fg: { veggies: 0.5  } },
  { id: 'side-cucumber',   name: 'Cucumber Slices',      emoji: '🥒', veggie: true, fg: { veggies: 0.25 } },
  { id: 'side-salad',      name: 'Side Salad',           emoji: '🥗', veggie: true, fg: { veggies: 1    } },
  { id: 'side-broccoli',   name: 'Broccoli',             emoji: '🥦', veggie: true, fg: { veggies: 0.5  } },
  { id: 'side-corn',       name: 'Corn',                 emoji: '🌽', veggie: true, fg: { veggies: 0.5  } },
  { id: 'side-celery',     name: 'Celery Sticks',        emoji: '🥬', veggie: true, fg: { veggies: 0.25 } },
  // ── Dairy ──────────────────────────────────────────────────────────────────
  { id: 'side-milk',       name: 'Glass of Milk',        emoji: '🥛', dairy: true, protein: true, fg: { dairy: 1, protein: 1 } },
  { id: 'side-yogurt',     name: 'Yogurt Cup',           emoji: '🫙', dairy: true, protein: true, fg: { dairy: 1, protein: 1 } },
  { id: 'side-cheese',     name: 'Cheese Slice',         emoji: '🧀', dairy: true, protein: true, fg: { dairy: 0.67, protein: 1 } },
  { id: 'side-choc-milk',  name: 'Chocolate Milk',       emoji: '🥛', dairy: true, protein: true, fg: { dairy: 1, protein: 1 } },
  // ── Protein add-ons ────────────────────────────────────────────────────────
  { id: 'side-chicken',    name: 'Grilled Chicken',      emoji: '🍗', protein: true, fg: { protein: 3 } },
  { id: 'side-fish',       name: 'Fish / Tuna',          emoji: '🐟', protein: true, fg: { protein: 3 } },
  { id: 'side-beans',      name: 'Black Beans',          emoji: '🫘', protein: true, carbs: true, fg: { protein: 2, veggies: 0.5 } },
  { id: 'side-egg',        name: 'Hard Boiled Egg',      emoji: '🥚', protein: true, fg: { protein: 1 } },
  // ── Carb sides ─────────────────────────────────────────────────────────────
  { id: 'side-fries',      name: 'French Fries',         emoji: '🍟', carbs: true,  fg: { veggies: 0.5 } },
  { id: 'side-bread',      name: 'Dinner Roll / Bread',  emoji: '🍞', carbs: true,  fg: { grains: 1   } },
  { id: 'side-rice',       name: 'Side of Rice',         emoji: '🍚', carbs: true,  fg: { grains: 1.5 } },
];

const WORKOUTS = [
  // sport:true = game/meet/match → triggers pre-game meal + snack rules
  { id: 'soccer-game',   name: 'Soccer Game',          emoji: '⚽', duration: 90,  halftime: true,  intensity: 'high',   sport: true  },
  { id: 'soccer-prac',   name: 'Soccer Practice',      emoji: '⚽', duration: 90,  halftime: false, intensity: 'medium', sport: false },
  { id: 'soccer-short',  name: 'Soccer Session (30 min)', emoji: '⚽', duration: 30,  halftime: false, intensity: 'medium', sport: false },
  { id: 'bball-game',    name: 'Basketball Game',       emoji: '🏀', duration: 60,  halftime: true,  intensity: 'high',   sport: true  },
  { id: 'bball-prac',    name: 'Basketball Practice',   emoji: '🏀', duration: 60,  halftime: false, intensity: 'medium', sport: false },
  { id: 'swim-meet',     name: 'Swim Meet',             emoji: '🏊', duration: 120, halftime: false, intensity: 'high',   sport: true  },
  { id: 'swim-prac',     name: 'Swim Practice',         emoji: '🏊', duration: 60,  halftime: false, intensity: 'high',   sport: false },
  { id: 'volleyball',    name: 'Volleyball',            emoji: '🏐', duration: 60,  halftime: false, intensity: 'medium', sport: true  },
  { id: 'lacrosse',      name: 'Lacrosse',              emoji: '🥍', duration: 60,  halftime: true,  intensity: 'high',   sport: true  },
  { id: 'tennis',        name: 'Tennis',                emoji: '🎾', duration: 60,  halftime: false, intensity: 'high',   sport: true  },
  { id: 'softball',      name: 'Softball / Baseball',   emoji: '⚾', duration: 90,  halftime: false, intensity: 'medium', sport: true  },
  { id: 'hitting-lesson', name: 'Hitting Lesson',       emoji: '⚾', duration: 60,  halftime: false, intensity: 'medium', sport: false },
  { id: 'playing-catch',  name: 'Playing Catch',        emoji: '⚾', duration: 30,  halftime: false, intensity: 'low',    sport: false },
  { id: 'ball-girl',      name: 'Ball Girl',            emoji: '⚾', duration: 90,  halftime: false, intensity: 'low',    sport: false },
  // Training & Fitness
  { id: 'gymnastics',    name: 'Gymnastics',            emoji: '🤸', duration: 90,  halftime: false, intensity: 'medium', sport: false },
  { id: 'dance',         name: 'Dance Practice',        emoji: '💃', duration: 60,  halftime: false, intensity: 'medium', sport: false },
  { id: 'run-short',     name: 'Short Run (20-30 min)', emoji: '🏃', duration: 25,  halftime: false, intensity: 'medium', sport: false },
  { id: 'run-long',      name: 'Long Run (45+ min)',    emoji: '🏃', duration: 50,  halftime: false, intensity: 'high',   sport: false },
  { id: 'strength-s',    name: 'Strength (short)',      emoji: '💪', duration: 20,  halftime: false, intensity: 'medium', sport: false },
  { id: 'strength-l',    name: 'Strength (long)',       emoji: '🏋️', duration: 60,  halftime: false, intensity: 'high',   sport: false },
  { id: 'yoga',          name: 'Yoga / Stretching',     emoji: '🧘', duration: 45,  halftime: false, intensity: 'low',    sport: false },
  { id: 'cheer',         name: 'Cheer / Pom',           emoji: '📣', duration: 90,  halftime: false, intensity: 'medium', sport: false },
];
